/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  mainSidebar: [{type: 'autogenerated', dirName: '.'}],
  // k1stSidebar: [
  //   {
  //     type: 'category',
  //     label: 'K1s Terminal',
  //     // link: {
  //     //   type: 'generated-index',
  //     //   title: 'Kubernetes K1s Serverless cluster',
  //     //   description: 'The best way to learn Kubernetes is by doing, and K1s, a Kubernetes serverless cluster will help you quickly get to grips with the technology.',
  //     //   slug: '/k1st/getting-started',
  //     //   keywords: ['Kubernetes', 'Kubernetes Serverless', 'Kubernetes API'],
  //     //   image: '/img/docusaurus.png',
  //     // },
  //     items: ['k1s-terminal'],
  //   },
  // ],
  // k1ssSidebar: [
  //   {
  //     type: 'category',
  //     label: 'K1ss Serverless',
  //     items: ['k1s-serverless'],
  //   },
  // ],
};

module.exports = sidebars;
